"""Per-quarter full-prompt logger.

Captures the full system prompt, user prompt, and response of every LLM
call made during a designated "logged quarter", and writes them into a
human-readable text file in pairs (call → response) ordered by start
timestamp. Activated via `RunConfig.prompt_log_every_n_quarters` (default
20: every 20 quarters write a detailed log; set to 0 to disable).

How activation works
--------------------
At the start of each quarter, the orchestrator calls
`activate_for_quarter(run_dir, quarter)` which decides whether the
current quarter is on the schedule. If yes, the module enters "active"
state and every wrapped LLMBackend appends to the per-quarter log file.
At the end of the quarter `deactivate()` is called and the file is
flushed.

How wrapping works
------------------
At run setup, `cli.py` wraps every concrete backend with
`LoggingBackend(inner_backend, fallback_role=...)`. The wrapper is
free when inactive (one boolean check); on active quarters it captures
both prompts plus the response and emits a single block to the log
file. The block structure is:

    ============================================================
    CALL #<seq>  Q<quarter>  <iso8601-timestamp>
    role:  <role from ContextVar>
    model: <model name>
    backend: <backend name>
    -- system prompt --
    <full system text>
    -- user prompt --
    <full user text>
    -- response (received <iso8601-timestamp>, latency <ms>) --
    <full response text>
    ============================================================

Concurrency note: parallel firm-decision pools issue many LLM calls
simultaneously. We use a process-wide threading.Lock around file
appends so blocks don't interleave. The seq counter is shared.
"""
from __future__ import annotations

import os
import threading
import time
from datetime import datetime, timezone
from pathlib import Path

from .llm_backends import LLMBackend


# Module-level state. Threadsafe via _LOCK.
_LOCK = threading.Lock()
_ACTIVE: bool = False
_LOG_PATH: Path | None = None
_SEQ: int = 0
_QUARTER: int = 0


def is_active() -> bool:
    """Cheap, lock-free read for the hot path. Slightly racy at the
    activation boundary but harmless — worst case is a stale-by-one-call
    log decision."""
    return _ACTIVE


def activate(log_path: Path, quarter: int) -> None:
    """Enable prompt logging for the current quarter, writing to log_path."""
    global _ACTIVE, _LOG_PATH, _SEQ, _QUARTER
    with _LOCK:
        log_path.parent.mkdir(parents=True, exist_ok=True)
        # Open with a header so the file is self-describing.
        header = (
            f"# Quarter Q{quarter} — full LLM prompt + response log\n"
            f"# Generated by src/prompt_logger.py at "
            f"{datetime.now(timezone.utc).isoformat()}\n"
            f"# One entry per LLM call. Calls and responses are paired in\n"
            f"# the same block. Across-call ordering is by call-start time.\n"
            f"#\n"
            f"# To search for a specific role: grep '^role:'\n"
            f"# To count calls: grep -c '^CALL '\n"
            f"#\n\n"
        )
        log_path.write_text(header, encoding="utf-8")
        _ACTIVE = True
        _LOG_PATH = log_path
        _SEQ = 0
        _QUARTER = int(quarter)


def deactivate() -> None:
    global _ACTIVE, _LOG_PATH
    with _LOCK:
        _ACTIVE = False
        # Keep _LOG_PATH so a final summary line could be appended later
        # if desired; not strictly necessary.
        _LOG_PATH = None


def activate_for_quarter(run_dir: Path, quarter: int,
                            every_n: int) -> Path | None:
    """Decide whether to log this quarter; if yes, create the log file
    and return its path. If not, return None.

    Schedule: log when `every_n > 0` AND `quarter % every_n == 0`. Quarter
    indices in the orchestrator are 1-based, so the first logged
    quarter is `every_n` (e.g. Q20, Q40, Q60, Q80 with every_n=20).
    Quarter 0 is never logged (it's a no-op anyway).
    """
    if every_n <= 0 or quarter <= 0:
        return None
    if quarter % every_n != 0:
        return None
    log_dir = Path(run_dir) / "prompt_logs"
    log_path = log_dir / f"Q{quarter:02d}_full_log.txt"
    activate(log_path, quarter)
    return log_path


def _record(role: str, model: str, backend: str,
             system: str, user: str, response: str,
             latency_ms: float, call_start_ts: str) -> None:
    """Append one block to the active log file. No-op if not active."""
    global _SEQ
    if not _ACTIVE or _LOG_PATH is None:
        return
    with _LOCK:
        _SEQ += 1
        seq = _SEQ
        # Render the block. Use a triple-line separator and explicit
        # field labels so a human can scan or grep.
        sep = "=" * 70
        ts_resp = datetime.now(timezone.utc).isoformat()
        block = (
            f"{sep}\n"
            f"CALL #{seq:04d}  Q{_QUARTER}  {call_start_ts}\n"
            f"role:    {role or 'unattributed'}\n"
            f"model:   {model or '?'}\n"
            f"backend: {backend or '?'}\n"
            f"-- system prompt --\n"
            f"{system}\n"
            f"-- user prompt --\n"
            f"{user}\n"
            f"-- response (received {ts_resp}, latency "
            f"{latency_ms:.0f} ms) --\n"
            f"{response}\n"
            f"{sep}\n\n"
        )
        try:
            with open(_LOG_PATH, "a", encoding="utf-8") as f:
                f.write(block)
        except Exception:
            # Logging must never disrupt the run.
            pass


class LoggingBackend(LLMBackend):
    """Wraps any LLMBackend. When the module is `is_active()` (set at
    quarter-boundary by the orchestrator), every call's prompt and
    response are appended to the active log file. When not active, the
    wrapper has the cost of one boolean check + a passthrough.
    """

    def __init__(self, inner: LLMBackend, fallback_role: str = "",
                  fallback_model: str = "", fallback_backend: str = ""):
        self._inner = inner
        self._fallback_role = fallback_role
        # Pull model + backend from the inner if available; fall back to
        # the explicit values passed at construction.
        self._fallback_model = fallback_model or getattr(inner, "model", "?")
        self._fallback_backend = fallback_backend or self._derive_backend()

    def __getattr__(self, item):
        # Anything not defined on LoggingBackend (e.g. .model, .temperature,
        # .timeout) passes through to the inner backend so the role-tagger
        # outer wrapper still sees the original attributes.
        return getattr(self._inner, item)

    def _derive_backend(self) -> str:
        cls = self._inner.__class__.__name__.lower()
        for name in ("openrouter", "minimax", "aihorde", "ollama", "mock"):
            if name in cls:
                return name
        return cls

    def _resolved_role(self) -> str:
        try:
            from . import telemetry as _tel
            return _tel.current_role() or self._fallback_role
        except Exception:
            return self._fallback_role

    def complete(self, system: str, user: str) -> str:
        if not is_active():
            return self._inner.complete(system, user)
        ts_call = datetime.now(timezone.utc).isoformat()
        t0 = time.time()
        try:
            response = self._inner.complete(system, user)
        except Exception as e:
            # Still log the failure so the audit trail is complete.
            _record(
                role=self._resolved_role(),
                model=self._fallback_model,
                backend=self._fallback_backend,
                system=system,
                user=user,
                response=f"<EXCEPTION: {type(e).__name__}: {e}>",
                latency_ms=(time.time() - t0) * 1000.0,
                call_start_ts=ts_call,
            )
            raise
        _record(
            role=self._resolved_role(),
            model=self._fallback_model,
            backend=self._fallback_backend,
            system=system,
            user=user,
            response=response or "",
            latency_ms=(time.time() - t0) * 1000.0,
            call_start_ts=ts_call,
        )
        return response

    def complete_json(self, system: str, user: str, retries: int = 2):
        # Forward complete_json directly to the inner backend so its
        # native JSON-parsing logic (with provider-specific retries,
        # rate-limit handling, etc.) is preserved. When logging is
        # active, capture the JSON response too — but cheaply, by
        # serializing the dict result.
        if not is_active():
            return self._inner.complete_json(system, user, retries=retries)
        ts_call = datetime.now(timezone.utc).isoformat()
        t0 = time.time()
        try:
            result = self._inner.complete_json(system, user, retries=retries)
        except Exception as e:
            _record(
                role=self._resolved_role(),
                model=self._fallback_model,
                backend=self._fallback_backend,
                system=system,
                user=user,
                response=f"<EXCEPTION: {type(e).__name__}: {e}>",
                latency_ms=(time.time() - t0) * 1000.0,
                call_start_ts=ts_call,
            )
            raise
        # Render the parsed JSON back to a readable string for the log.
        if result is None:
            response_text = "<None — JSON parse failed>"
        else:
            try:
                import json as _json
                response_text = _json.dumps(result, indent=2,
                                              ensure_ascii=False, default=str)
            except Exception:
                response_text = repr(result)[:5000]
        _record(
            role=self._resolved_role(),
            model=self._fallback_model,
            backend=self._fallback_backend,
            system=system,
            user=user,
            response=response_text,
            latency_ms=(time.time() - t0) * 1000.0,
            call_start_ts=ts_call,
        )
        return result
